### ISSUE TITLE
this.CookieFirst.acceptAllCategories is not a function

### ISSUE THREAD

**Issue by noah-stahl** [ChristianBielak/VueCookieFirst#1]
Hello, thank you for this repository, but unfortunately I am having some trouble getting it to work. I integrated it as described in your documentation, and the banner shows up, although it looks like without any styling, 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/37332832/83644166-485bed80-a5b1-11ea-8707-c248d264e6e3.png">
but when I try to click either of the buttons, nothing happens and the following error shows up in the console

`TypeError: "this.CookieFirst.acceptAllCategories is not a function"`

Also I have noticed that you insert a script tag with the src `https://consent.cookiefirst.com/banner.js`into the head, but in the CookieFirst dashboard they instruct me to insert a script tag with the src `https://consent.cookiefirst.com/banner.js` into the body, why is that?

**Comment by ChristianBielak** [comment]
Do you pass your api key as prop? Otherwise the CookieFirst object is not present.

At the moment I am not very happy with the implementation of the script. But Cookiefirst offers no other option. I am currently in contact with the developers to find a better solution for the implementation.
